apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dify-ingress
  namespace: dify
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: "/"
    alb.ingress.kubernetes.io/load-balancer-name: "dify-alb" 
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/load-balancer-attributes: "idle_timeout.timeout_seconds=3600"
    alb.ingress.kubernetes.io/certificate-arn: '{{ .Values.domains.certArn }}'
    alb.ingress.kubernetes.io/headers: >-
      [{"key": "Access-Control-Allow-Origin", "value": "*"},
       {"key": "Access-Control-Allow-Methods", "value": "GET, OPTIONS, PUT, POST, DELETE, PATCH"},
       {"key": "Access-Control-Allow-Headers", "value": "Content-Type, Authorization"},
       {"key": "Access-Control-Allow-Credentials", "value": "true"},
       {"key": "Access-Control-Max-Age", "value": "100"},
       {"key": "Strict-Transport-Security", "value": "max-age=63072000; includeSubDomains; preload"}]
spec:
  ingressClassName: alb
  rules:
    - host: {{ .Values.domains.siteDomain }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: dify-api
                port:
                  number: 5001
          - path: /console/api
            pathType: Prefix
            backend:
              service:
                name: dify-api
                port:
                  number: 5001
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: dify-api
                port:
                  number: 5001
          - path: /files
            pathType: Prefix
            backend:
              service:
                name: dify-api
                port:
                  number: 5001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dify-web
                port:
                  number: 3000
  # tls:
  #   - secretName: dify-tls
