apiVersion: v1
kind: PersistentVolume
metadata:
  name: dify-api-storage-pv
spec:
  capacity:
    storage: {{ .Values.volume.storageSize }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - allow-delete
    - allow-other
    - allow-overwrite
    - region {{ .Values.volume.awsRegion }}
    - prefix dify-api/
  csi:
    driver: s3.csi.aws.com 
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: {{ .Values.volume.s3Bucket }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dify-api-storage-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "" 
  resources:
    requests:
      storage: {{ .Values.volume.storageSize }}
  volumeName: dify-api-storage-pv
---
